INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1001,'Spider Man 2002','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1002,'Fast 5','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1003,'Iron Man','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1004,'The Avengars','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1005,'THOR','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1006,'Tokyo Drift','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1007,'The Green Mile','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1008,'The Green Mile 2','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1009,'TROY','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1010,'The Age','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1011,'The Age1','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1012,'The Age2','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1013,'The Age3','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1014,'The Age4','http://image','The Begining of spider',7);
INSERT INTO MOVIE(id,title,image_uri,description,rate) VALUES (1015,'The Age5','http://image','The Begining of spider',7);
